server:
  port: 8099
spring:
  application:
    name: demo-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.pojos